[package]
name = "portman"
version = "0.3.0"
authors = ["Caleb Cox"]
edition = "2021"
description = "Local port allocation manager"
readme = "README.md"
repository = "https://github.com/canac/portman"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = { version = "3.1.8", features = ["derive"] }
directories = "4.0.1"
entrait = { version = "0.4.6", features = ["unimock"] }
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.5.5"
serde = { version = "1.0.136", features = ["derive"] }
toml = "0.5.8"
unimock = "0.3.14"

[build-dependencies]
clap = { version = "3.1.8", features = ["derive"] }
clap_complete = "3.1.1"
clap_complete_fig = "3.1.4"
clap_mangen = "0.1.2"
