[package]
name = "portman"
version = "0.2.2"
authors = ["Caleb Cox"]
edition = "2021"
description = "Local port allocation manager"
readme = "README.md"
repository = "https://github.com/canac/portman"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
directories = "4.0.1"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.5.5"
serde = { version = "1.0.136", features = ["derive"] }
structopt = "0.3.26"
thiserror = "1.0.30"
toml = "0.5.8"

[build-dependencies]
clap = { version = "3.1.8", features = ["derive"] }
clap_complete = "3.1.1"
clap_complete_fig = "3.1.4"
clap_mangen = "0.1.2"
