[package]
name = "portman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
directories = "4.0.1"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.5.5"
serde = { version = "1.0.136", features = ["derive"] }
structopt = "0.3.26"
thiserror = "1.0.30"
toml = "0.5.8"
