# `ranges` tells portman which ranges of ports can be assigned to projects. It
# is an array of two-item arrays. The first item is the start of the port range
# and the second item is the end of the port range.
#
# Example (assigns ports from 3000-3099 and 3200-3299):
# ranges = [[3000, 3099], [3200, 3299]]
ranges = [[3000, 3999]]

# `reserved` overrides `ranges` and tells portman which ports to never assign.
# It is an array of integers.
#
# Example (assigns ports in `ranges` except for 3210 and 3121):
# reserved = [3210, 3121]
reserved = []
