name: End to end tests
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path .
      - run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && ./e2e/setup.sh && ./e2e/test_fish.fish
