name: End-to-end tests
on: [push, pull_request]

jobs:
  test:
    name: E2E (${{ matrix.shell }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - shell: bash
          - shell: fish
          - shell: zsh
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path .
      - run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          ./e2e/setup.sh
          ./e2e/test_${{ matrix.shell }}.${{ matrix.shell }}
