name: End-to-end tests
on: [push, pull_request]

jobs:
  test:
    name: E2E (${{ matrix.shell }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - shell: bash
          - shell: fish
          - shell: zsh
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install --path .
      - run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          ./e2e/setup.sh
          ./e2e/test_${{ matrix.shell }}.${{ matrix.shell }}
